[book]
title = "Axum Tutorial"
authors = ["Programatik"]
description = "A complete axum web framework tutorial."
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/programatik29/axum-tutorial"
